### ISSUE TITLE
Support for Event with the details of the next scheduled appointment

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-child#238]
Add support for configurable autogeneration of an event with the details of the next scheduled appointment.

**Event name:** `next_vaccine_date`

- [x] Event name `next_vaccine_date`
- [x] Configurable via property `next.appointment.event.enabled`
- [x] Contains observation fields listed below

**Relevant Obs fields :**
 
- Vaccine Given
- Whether Vaccine was out of catchment
- Next Appointment Date
- Next Vaccine Due

**Other data :**
- BaseEntityId (collected by default for any OpenSRP Event)

**Comment by dubdabasoduba** [comment]
**Where this was to be used.** 
- Was to be integrated with SMSes (Not RapidPro).
